version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name my-web-app --s3-location s3://my-company-deploy-artifacts-2025/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
